openapi: 3.0.3
info:
  title: Revision API
  version: 1.0.0
servers:
  - url: https://revision.com
paths:
  /books:
    get:
      summary: Get all books
      description: Return all books ordered by author
      operationId: getBooks
      parameters:
        - in: query
          name: bookName
          description: Filter the returned books by the given name
          required: false
          schema:
            type: string
      responses:
        200:
          description: The returned books
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  bookName:
                    type: string
                  author:
                    type: string
                  releaseDate:
                    format: date
    put:
      summary: The list of created or updated books
      description: Updated books
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: 
                $ref: '#/components/schemas/Book'
      responses:
        200:
          description: The list of created or updated books
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Book'
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: string
        bookName:
          type: string
        author:
          type: string
        releaseDate:
          format: date
        topic:
          $ref: '#/components/schemas/Topic'
    Topic:
      type: string
      enum:
        - ROMANCE
        - COMEDY
        - DRAMA
        - OTHER
